# Generated by Django 4.1.7 on 2023-04-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_category_tip_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
